spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutorialsecurity
    username: postgres
    password: 102030
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-value: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  jwt:
    secret: 28482B4D6250655368566D597133743677397A24432646294A404E635266546A
    # expirationMs: 